//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BMEntities6 : DbContext
    {
        public BMEntities6()
            : base("name=BMEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<THUEXE> THUEXEs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    
        public virtual int pDangKiThueXe(string sDT, Nullable<System.DateTime> ngayDangKi, Nullable<System.DateTime> ngayBD)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngayDangKiParameter = ngayDangKi.HasValue ?
                new ObjectParameter("NgayDangKi", ngayDangKi) :
                new ObjectParameter("NgayDangKi", typeof(System.DateTime));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pDangKiThueXe", sDTParameter, ngayDangKiParameter, ngayBDParameter);
        }
    
        public virtual int pDangKiThueXe1(string sDT, Nullable<System.DateTime> ngayDangKi, Nullable<System.DateTime> ngayBD, string diachi, Nullable<System.DateTime> ngaysinh, string ten, string cmnd)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngayDangKiParameter = ngayDangKi.HasValue ?
                new ObjectParameter("NgayDangKi", ngayDangKi) :
                new ObjectParameter("NgayDangKi", typeof(System.DateTime));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pDangKiThueXe1", sDTParameter, ngayDangKiParameter, ngayBDParameter, diachiParameter, ngaysinhParameter, tenParameter, cmndParameter);
        }
    }
}
