//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public System.DateTime NgayDangKi { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
        public string DiaChi_NhanXe { get; set; }
        public string DiaChi_TraXe { get; set; }
        public int TongTien { get; set; }
    }
}
