//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUEXE
    {
        public string MaXe { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
