//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUEXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUEXE()
        {
            this.FEEDBACKs = new HashSet<FEEDBACK>();
        }
    
        public string MaHD { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgayDangKi { get; set; }
        public System.DateTime NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
